f1=input('Input the first sine frequency ');
f2=input('Input the second sine frequency ');
a1=input('Input the first sine amplitude ');
a2=input('Input the second sine amplitude ');
x=0:.001:3;
y1=a1*sin(2*pi*f1*x);
y2=a2*sin(2*pi*f2*x);
subplot(3,1,1);
plot(x,y1);
title('Sine1');
xlabel('Time(t)');
ylabel('y1(t)');
subplot(3,1,2);
plot(x,y2);
title('Sine2');
xlabel('Time(t)');
ylabel('y2(t)');
z=y1+y2;
subplot(3,1,3);
plot(x,z);
title('Sine1 + Sine2');
xlabel('Time');
ylabel('y1(t)+y2(t)'); 
