wc=0.5*pi;
N=120;
alpha=(N-1)/2;
eps=0.001;
n=0:1:N-1;
hd=sin(wc*(n-alpha + eps))./(pi*(n-alpha + eps));
wh=hanning(N);
hn=hd.*wh';
w=0:0.01:pi;
h=freqz(hn,1,w);
subplot(311);
stem(n,wh);
xlabel('n');
ylabel('wh[n]');
title('Hanning window');
subplot(312);
stem(n,hn);
xlabel('n');
ylabel('h[n]');
title('Ideal impulse response');
subplot(313);
plot(w/pi,abs(h));
grid on;
xlabel('Normalized frequency');
ylabel('Magnitude');
title('Magitude response');
gtext('Noufal P 13400043');