clc;
clear all;
delay = input('Enter Delay ');
snr=input('Enter SNR in dB ');
t=1:1000;
y=sin(24*pi*t/100);
x=zeros(1,1000);
refer=[y x x x x x x x x];
subplot(311);
plot(refer);
title('reference signal');
transmit=[zeros(1,delay) y x x x x x x x zeros(1,1000-delay)];
transmit=awgn(transmit,snr);
subplot(312);
plot(transmit);
title('delayed signal');
l=min(length(refer),length(transmit))-1;
[xcf,lags,bounds]=crosscorr(refer,transmit,l);
subplot(313);
plot(lags,xcf);
title('cross-correlation plot');
[m i] = max(xcf);
display(lags(i));
